### ISSUE TITLE
Do we capitalize the Resolver Types

### ISSUE THREAD

**Issue by moonshiner** [bortzmeyer/my-IETF-work#3]
I'm wondering if the names of the resolver types: such as Caching Resolver, Full Resolver, Recursive Resolver, etc 

Should they match the names in the DNS terminology draft

**Comment by bortzmeyer** [comment]
https://tools.ietf.org/html/draft-hoffman-dns-terminology-01 does not use capitals. I quote "The protocol
   interfaces for DNS forwarders are exactly the same as those for
   recursive resolvers (for interactions with DNS stubs) and as those
   for stub resolvers (for interactions with recursive resolvers)."

**Comment by moonshiner** [comment]
Agreed to follow the terminology draft.  Bikeshedding complete here.
